os:
  - linux
  - windows

language: node_js

node_js:
  - 6
  - 10
  - 12

env:
  - TERSER_TEST_ALL=1

matrix:
  fast_finish: true
  exclude:
    - node_js: 6
      os: windows
    - node_js: 10
      os: windows

cache:
  directories:
    - tmp
    - node_modules

jobs:
  include:
    - name: Functional tests
      script: |
        test/functional.sh
      node_js: 13
      os: linux
      if: branch = master
      cache:
        directories:
          - node_modules
            terser-functional-tests
